### ISSUE TITLE
seems something wrong with code 'run_friends_split_context.py' and 'friendsqa.py'

### ISSUE THREAD

**Issue by zz-fortune** [emorynlp/FriendsQA#2]
when i try to run the code 'run_friends_split_context.py', it can not build the model from pretrain. After i fixed this bug, another bug cames. 

It seems there are many tiny bugs in this code! would you fix it?

thanks

**Comment by FrankLicm** [comment]
Sorry, yes, there may be some small bugs because I have refactored the code to fit the updated huggingface transformer repo versions(I developed the models about a year ago and the architecture of their resp changed a lot), so the things I now only can make sure it is totally correct are the models codes, but some bugs may happen in the top-level files. Since I stopped doing this project for about half year so I may cannot fix them, but you can ask for some specific bugs. I'll try my best to help you!!!

**Comment by arianakc** [comment]
Hi I fixed the bugs, you may retry, but just a warning that this model requires large GPU memory to run at least 24 G or 32G GPU memory and you need first to do pre-training to get a good result. And compared to our model, the best baseline model: the whole context fine-tuning Roberta-base only performed a little worse, and we tried our approach on many other dialogue-based tasks such as other Character Mining tasks which did not perform well. So this is time-consuming but the gains are very little and rerun all pretraining and fine-tune processes are actually kind of meaningless and waste of time. To save your time,  I just recommend you first start from the whole context fine-tuning Roberta-large model which can have a shorter time to run and may get even better results since we couldn't use it before due to GPU memory limitation. Also, I refactored code to fit for the updated hugging face transformers repo architecture so there may be some small bugs like inconsistent or missing variables. Since I moved to a new project and very busy now,  I am sorry that I may not have time to check and fix all of them. But if you have some specific problems, we can discuss it when I have time. In that case, please send me an email to llccmm118@gmail.com. Thank you.
