### ISSUE TITLE
HOW TO RUN uop.py

### ISSUE THREAD

**Issue by cn-boop** [emorynlp/FriendsQA#3]
All files in processors folder just consist functions but don't have programing running entrance(like __name__=__main__).how can I run this files?

**Comment by arianakc** [comment]
You need to first generate training instances from a corpus then use run_uop.py to run. Please see the Huggingface Transformers framework for the reference.

**Comment by cn-boop** [comment]
thx，but how to generate training instances from a corpus?

**Comment by cn-boop** [comment]
i mean i want to use Friendsqa as  my training datasets, so how to generate training instances from  this datasets

**Comment by arianakc** [comment]
You need to write code to generate it into the format in the readme or you can change the format you like in uop.py. This repo does not include that generation code. I cannot give it to you now because my computer had water damage few weeks ago and all codes were lost. Besides, I suggest you don't need to waste time on it because I tried this approach on many other Friends dialogue tasks and it didn't work. So I did not work on this anymore for more than half year so some details are forgotten.

**Comment by cn-boop** [comment]
Thanks
